baseURL = 'https://awsugg-website.s3.us-east-2.amazonaws.com/'
languageCode = 'es-gt'
title = 'AWS User Group Guatemala'
theme = "awsug"
summaryLength = '35'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Inicio"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "Quiénes Somos"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier = "team"
    name = "Voluntarios"
    url = "/team/"
    weight = 30
  [[menu.main]]
    identifier = "events"
    name = "Eventos"
    url = "/events/"
    weight = 40
  [[menu.main]]
    identifier = "blog"
    name = "Publicaciones"
    url = "/blog/"
    weight = 50

[deployment]

[[deployment.targets]]
name = "production"
URL = "s3://awsugg-website?region=us-east-2"
#cloudFrontDistributionID = "E2RPNIMVK40BRV"